server:
  port: 80
  tomcat:
    uri-encoding: UTF-8
# 数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/january?characterEncoding=utf-8
    username: root
    password: 1
    # 初始化大小、最小、最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 获取连接等待超时时间
    maxWait: 30000
    # 清理空闲连接的间隔时间
    timeBetweenEvictionRunsMillis: 60000
    # 连接在连接池中最小生存时间
    minEvictableIdleTimeMillis: 300000
    validationiQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并指定每个连接上PSCache大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    